package main;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.io.IOException;
import javax.swing.JComboBox;
import javax.swing.JToggleButton;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static javax.swing.WindowConstants.EXIT_ON_CLOSE;
import javax.swing.plaf.nimbus.NimbusLookAndFeel;

/**
 * Entry class and GUI
 *
 * @author David C
 */
public class Window extends javax.swing.JFrame {

    // Version
    public static final double VERSION = 1.2;

    // Main objects
    private static Code code;
    private static Window gui;

    /**
     * Main method entry point
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        // Set look and feel
        try {
            UIManager.setLookAndFeel(new NimbusLookAndFeel());
        } catch (UnsupportedLookAndFeelException e) {
            System.err.print(e.toString());
            System.exit(1);
        }

        // Create GUI
        java.awt.EventQueue.invokeLater(() -> {
            try {
                // Initialize GUI and tools
                gui = new Window();
                code = new Code(gui, args);

                // Make adjustments to frame
                gui.setVisible(true);
                gui.setTitle("DayStarter V" + VERSION + " - by David C, 2019");

                Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
                int frameXPos = ((int) screen.getWidth() / 2) - (gui.getWidth() / 2);
                gui.setLocation(frameXPos, 39);

                gui.setResizable(false);
                gui.setDefaultCloseOperation(EXIT_ON_CLOSE);

                // Setup list of possible template options
                code.loadTemplates();

            } catch (HeadlessException | IOException e) {
                System.err.print(e.toString());
                System.exit(1);
            }
        });

    }

    /**
     * Creates GUI
     */
    public Window() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JMenuBar jMenuBar2 = new javax.swing.JMenuBar();
        javax.swing.JMenu jMenu3 = new javax.swing.JMenu();
        javax.swing.JMenu jMenu4 = new javax.swing.JMenu();
        javax.swing.JMenuItem jMenuItem1 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem2 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem3 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem4 = new javax.swing.JMenuItem();
        javax.swing.JMenuItem jMenuItem6 = new javax.swing.JMenuItem();
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel title = new javax.swing.JLabel();
        javax.swing.JButton startBut = new javax.swing.JButton();
        javax.swing.JLabel question1 = new javax.swing.JLabel();
        javax.swing.JComboBox<String> combo2 = new javax.swing.JComboBox<>();
        javax.swing.JLabel question2 = new javax.swing.JLabel();
        javax.swing.JToggleButton tmrwBut = new javax.swing.JToggleButton();
        javax.swing.JComboBox<String> combo1 = new javax.swing.JComboBox<>();
        javax.swing.JMenuBar jMenuBar1 = new javax.swing.JMenuBar();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 450));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 450));

        panel.setBackground(new java.awt.Color(255, 182, 81));
        panel.setForeground(new java.awt.Color(255, 255, 255));
        panel.setName("panel"); // NOI18N
        panel.setPreferredSize(new java.awt.Dimension(800, 450));

        title.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(0, 0, 0));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("DayStarter");
        title.setName("title"); // NOI18N

        startBut.setBackground(new java.awt.Color(102, 102, 255));
        startBut.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        startBut.setForeground(new java.awt.Color(0, 0, 0));
        startBut.setText("Start your Amazing Day!");
        startBut.setToolTipText("");
        startBut.setAlignmentY(0.0F);
        startBut.setBorder(null);
        startBut.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        startBut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        startBut.setIconTextGap(0);
        startBut.setMargin(new java.awt.Insets(0, 0, 0, 0));
        startBut.setName("startBut"); // NOI18N
        startBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButAction(evt);
            }
        });

        question1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        question1.setForeground(new java.awt.Color(0, 0, 0));
        question1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question1.setText("What's happening today ?");
        question1.setName("question1"); // NOI18N

        combo2.setBackground(new java.awt.Color(255, 204, 0));
        combo2.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "None" }));
        combo2.setBorder(null);
        combo2.setName("combo2"); // NOI18N
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });

        question2.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        question2.setForeground(new java.awt.Color(0, 0, 0));
        question2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        question2.setText("Getting ready for tomorrow?");
        question2.setName("question2"); // NOI18N

        tmrwBut.setBackground(new java.awt.Color(255, 255, 0));
        tmrwBut.setFont(new java.awt.Font("Cambria", 1, 18)); // NOI18N
        tmrwBut.setText("I'm focusing on the present");
        tmrwBut.setActionCommand("");
        tmrwBut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tmrwBut.setBorderPainted(false);
        tmrwBut.setFocusPainted(false);
        tmrwBut.setFocusTraversalPolicyProvider(true);
        tmrwBut.setName("tmrwBut"); // NOI18N
        tmrwBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tmrwButActionPerformed(evt);
            }
        });

        combo1.setBackground(new java.awt.Color(255, 204, 0));
        combo1.setFont(new java.awt.Font("Cambria", 0, 18)); // NOI18N
        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None", "None" }));
        combo1.setBorder(null);
        combo1.setName("combo1"); // NOI18N
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(218, 218, 218)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(question1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(tmrwBut, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(254, 254, 254))))
            .addComponent(startBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(89, 89, 89)
                .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(question1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(combo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(question2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tmrwBut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(startBut, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jMenuBar1.setBorder(null);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * The actions of the 'tomorrow button'
     *
     * @param evt
     */
    private void tmrwButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tmrwButActionPerformed

        // Toggle between yellow and purple
        if (((JToggleButton) evt.getSource()).getBackground().equals(Color.magenta)) {
            ((JToggleButton) evt.getSource()).setBackground(Color.yellow);
            ((JToggleButton) evt.getSource()).setText("I'm focusing on the present");
        } else {
            ((JToggleButton) evt.getSource()).setBackground(Color.magenta);
            ((JToggleButton) evt.getSource()).setText("Yes!");
        }
    }//GEN-LAST:event_tmrwButActionPerformed

    /**
     * The actions of the Start Day Button
     *
     * @param evt
     */
    private void startButAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButAction

        // Holder
        String choices = "";

        // Process combo boxes and save choices
        choices += processComboBox(1);
        choices += ",";
        choices += processComboBox(2);

        // Save choices made
        code.saveChoices(choices);

        // Finish normally
        System.exit(0);
    }//GEN-LAST:event_startButAction

    /**
     * Process a given combo box
     *
     * @param CBnum
     * @return
     */
    private String processComboBox(int CBnum) {

        // Get path to template selected
        String CBname = code.getCBName(CBnum);
        JComboBox tempBut = (JComboBox) code.getComponentByName(CBname);
        String tempS = (String) tempBut.getModel().getSelectedItem();
        String tempName = "\\" + tempS + "T.docx";

        // Copy template from source to destination
        code.copyTemplate(tempName);

        // Get tomorrow status and new name
        JToggleButton tmrwBut = (JToggleButton) code.getComponentByName("tmrwBut");
        String newName = code.getNewName(tempS, tmrwBut.getText().length() < 6);

        // Rename template made
        code.renameTemplate(tempName, newName);

        // Return choice
        return tempS;
    }

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
